name: tests

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:

  unit:
    name: Run the unit tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: 3.11
      - name: Python info
        shell: bash -e {0}
        run: |
          which python
          python --version
      - uses: eWaterCycle/setup-apptainer@v2
        with:
          apptainer-version: 1.2.5
      - name: Apptainer info
        shell: bash -e {0}
        run: |
          which apptainer
          apptainer version
      - name: Upgrade pip and install dependencies
        run: |
          python -m pip install --upgrade pip setuptools
          python -m pip install .[dev]
      - name: Run unit tests on Linux
        run: |
          python -m pytest -v

  types:
    name: Type checking
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: 3.11
      - name: Python info
        shell: bash -e {0}
        run: |
          which python
          python --version
      - name: Upgrade pip and install dependencies
        run: |
          python -m pip install --upgrade pip setuptools
          python -m pip install .[dev]
      - name: Check static typing
        run: |
          mypy --install-types --extra-checks  --strict  kunefe

  lint:
    name: Linting the code
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: 3.11
      - name: Python info
        shell: bash -e {0}
        run: |
          which python
          python --version
      - name: Upgrade pip and install dependencies
        run: |
          python -m pip install --upgrade pip setuptools
          python -m pip install .[dev]
      - name: Check style against standards using ruff
        run: ruff .
